// Turns plan-progress's hooks/bar.ts into bar.js, a classic script the demo
// page loads (Chromium refuses module imports over file://), so the clip
// draws its bars with the plugin's own code.
//
//   node media/src/plan-progress/build-bar.mjs <path to plan-progress>/hooks/bar.ts
import { stripTypeScriptTypes } from 'node:module'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const source = process.argv[2]
if (!source) throw new Error('usage: node build-bar.mjs <path to bar.ts>')

const js = stripTypeScriptTypes(readFileSync(source, 'utf8'))
  .replace(/^export /gm, '')
const names = [...readFileSync(source, 'utf8').matchAll(/^export const (\w+)/gm)].map(m => m[1])

const out = `// Generated by build-bar.mjs from plan-progress hooks/bar.ts; do not edit.
var PlanBar = (() => {
${js}
return { ${names.join(', ')} }
})()
`
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), 'bar.js'), out)
console.log(`bar.js: ${names.join(', ')}`)
